context:
  name: csp-adapter-discord
  version: "0.1.2"
  python_min: '3.9'

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/c/csp-adapter-discord/csp_adapter_discord-${{ version }}.tar.gz
  sha256: c72acc6afd858fa5290d9623dc3228c8fb55f9ffc125b068747d352ef9473de4

build:
  number: 0
  noarch: python
  script: python -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - hatchling
  run:
    - python >=${{ python_min }}
    - csp
    - discord.py
    - pydantic >=2

tests:
  - python:
      imports:
        - csp_adapter_discord
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  license: Apache-2.0
  license_file: LICENSE
  summary: CSP adapter for Discord
  homepage: https://github.com/timkpaine/csp-adapter-discord
  repository: https://github.com/timkpaine/csp-adapter-discord

extra:
  recipe-maintainers:
    - timkpaine
